config/routes.rb
SampleApp::Application.routes.draw do
  resources :users 
  resources :hotels do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'hotels#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/listOfHotels', to: 'hotels#list_of_hotels', via: 'get'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
belongs_to :user
has_many :comments, dependent: :destroy

scope :top5, -> {
    select("hotels.id, hotels.title, hotels.star_rating, hotels.breakfast,
     hotels.image, hotels.room_desc, hotels.price, hotels.address,count(comments) AS comments_count").
    joins(:comments).
    group("hotels.id, hotels.title, hotels.star_rating,
     hotels.breakfast, hotels.image, hotels.room_desc, hotels.price, hotels.address").
    order("comments_count DESC").
    limit(5)
}
#Hotel.top5
validates :title, presence: true, length: {minimum:2, maximum:30}
#VALID_BREAK_REGEX = /\A+yes|no/
#validates :breakfast, presence: true, format: {with:VALID_BREAK_REGEX}
validates :room_desc, presence: true
validates :price, presence: true
validates :address, presence: true
validates :image, presence: true
mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :hotels, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  /def create
    @hotel = Hotel.find(params[:hotel_id])
    @comment = @hotel.comments.create(comment_params)
    @comment.user_id = current_user.id
    redirect_to hotel_path(@hotel)
  end/
 
  def create
    @hotel = Hotel.find(params[:hotel_id])
    @comment = Comment.create(comment_params)
    @comment.hotel_id = @hotel.id
    @comment.user_name = current_user.name
    if @comment.save
      redirect_to hotel_path(@hotel)
    else
      redirect_to hotel_path(@hotel)
    end
  end

  def destroy
    @hotel = Hotel.find(params[:hotel_id])
    @comment = @hotel.comments.find(params[:id])
    @comment.destroy
    redirect_to hotel_path(@hotel)
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
  	@hotel = Hotel.top5
  end
 
  def show
  	@hotel= Hotel.find(params[:id])     
  end

  def new
    @hotel = Hotel.new
  end

  def list_of_hotels
    @hotel = Hotel.all
  end

  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user_id = current_user.id
    if @hotel.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end
 
  def update
    @hotel = Hotel.find(params[:id])
 
    if @hotel.update(hotel_params)
      redirect_to current_user 
    else
      render 'edit'
    end
  end
 
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
 
    redirect_to current_user 
  end
 
  private
    def hotel_params
      params.require(:hotel).permit(:title, :star_rating, :breakfast, :room_desc, :price, :address, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
  else
    flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
  end
end

  def destroy
    sign_out
    redirect_to root_url
  end	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
	
  def show
    @user = User.find(params[:id])
    @hotel = @user.hotels.paginate(page: params[:page], per_page: 2)
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 100 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/blocks/_preview.html.erb
    <span class="content">
		<div class="div_preview_enrty">
    		<table class="table_preview_entry">
       		 <tr>
            	<td class="td_preview_pic">
                	<div class="table_preview_div1">
                		<%= image_tag hotel.image.thumb.url %>
               		</div>
           		</td>
      				<td class="td_preview_text"> 
             		 <div class"td_preview_text_div">
               		  <div class="table_preview_div2">
                		<%= hotel.title %>
               		  </div>
               			<div class="table_preview_div3">
                 		<%= hotel.room_desc %>
                      <div>
                        <%= hotel.breakfast %>
                      </div>
                      <div>
                        <%= hotel.address %>
                      </div>
               		  </div>
                		<div class="table_preview_div4">
               		    <%= hotel.star_rating %> stars
               		  </div>
               		  <div class="table_preview_div5">
                		<%= link_to "More", hotel_path(hotel), class: "btn btn-large btn-primary btn-more" %> 
               		  </div>
              		  <div class="table_preview_div6">
                		<%= hotel.price %>
               		  </div>
               		  <div class="clear"></div>              
             		 </div>             
            		</td>
       		 </tr>
   		 </table>
		</div>
	  </span>

app/views/blocks/_show_hotel.html.erb
<div class="center hero-unit">
    <h1>Full description about hotel</h1>
    <h1>
      <%= @hotel.title %>
    </h1>
    <hr />

    <div class="div_descr_1">
       <%= image_tag @hotel.image.thumb.url %>
    </div>

    <div class="div_descr_3">
        div 3 - Rating: <br />
        <%= @hotel.star_rating %>
    </div>

    <div class="div_descr_4">
        div 4 - Price: <br />
        <%= @hotel.price %>
    </div>   

    <div class="div_descr_5">
        div 5 - breakfast: <br />
        <%= @hotel.breakfast %>
    </div>  

    <div class="div_descr_2">
        <%= @hotel.room_desc %>
        <div>
            <br />
            <i>Address: &emsp;</i> <%= @hotel.address %>
        </div>  
    </div>

    
   
    <div class="clear"></div>
</div>

app/views/hotels/_form.erb
<%= form_for @hotel, html: { multipart: true } do |f| %>
 
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@hotel.errors.count, "error") %> prohibited
        this hotel from being saved:
      </h2>
      <ul>
        <% @hotel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Your hotel name"%>
  </p>

 <p>
    <%= f.label :star_rating %><br>
    <%= f.select(:star_rating, options_for_select([['1', '1'], 
                  ['2', '2'],['3', '3'],['4', '4'],['5', '5']])) %>
  </p>

  <p>
    <%= f.label :breakfast %><br>
    <%= f.select(:breakfast, options_for_select([['yes', 'yes'], 
                      ['no', 'no']],{ include_blank: true }))  %>
  </p>

  <p>
    <%= f.label :room_desc %><br>
    <%= f.text_area :room_desc, placeholder: "Tell about your hotel" %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price, placeholder: "Amount" %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address, placeholder: "Tell your hotel address" %>
  </p>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/hotels/edit.html.erb
<h1>Edit Hotel</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', current_user %>

app/views/hotels/index.html.erb
<% provide(:title, '') %>
<div class="main_pic">
    <br /><br /><br /><br />
    <div class="greeting_text">
        <h1 class="greeting_text">Find the lowest price on the right hotel for you</h1>
    </div>
    <div class="slogan_text">
        <center><h2><strong>
'Hotel App' is the only hotel site that sends special investigators to visit, 
photograph, review, and rate each hotel. We inspect in-person — just like your 
mother-in-law.
        </strong></h2></center></div>
    </div>

<div class="center hero-unit">
   	<h1>TOP 5 hotels</h1>
	<hr />
	<% @hotel.each do |hotel| %>

		<%= render :partial => 'blocks/preview', 
					:locals => {:hotel => hotel} %>
	<% end %>
</div>

app/views/hotels/list_of_hotels.html.erb
<% provide(:title, '') %>
<div class="center hero-unit">
    <h1>Full list of hotels</h1>
    <hr />
    <center>
        <% @hotel.each do |hotel| %>


        <%= render :partial => 'blocks/preview', 
                    :locals => {:hotel => hotel} %>
    <% end %>
    </center>
</div>

app/views/hotels/new.html.erb
<h1>New hotel</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', current_user %>

app/views/hotels/show.html.erb
<% provide(:title, '') %>
<%= render 'blocks/show_hotel' %>
<div class="center hero-unit"><h2>Comments</h2>
<% @hotel.comments.each do |comment| %> 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <strong>user_name:</strong>
    <%= comment.user_name %>
  </p>
  <% if signed_in? && @hotel.user_id == current_user.id %>
    <p>
    <%= link_to 'Destroy Comment', [comment.hotel, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
<% end %>
<% if signed_in? %>
  <h2>Add a comment:</h2>
  <%= form_for([@hotel, @hotel.comments.build]) do |f| %>
   <p>
     <%= f.label :body %><br>
     <%= f.text_area :body %>
   </p>
   <p>
     <%= f.submit %>
   </p>
  <% end %>
  <% else %>
  </br>
  <p>
    <strong>You should sign up to create a comment</strong>
  </p>
<% end %>
<%= link_to 'Back', root_path %></div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Simple web-application for hotel rating</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="top_menu">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Hotel App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Main board", root_path %></li>
          <li><%= link_to "List of hotels", listOfHotels_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Add hotel", '/hotels/new' %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Sign up now!", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <link rel="stylesheet" media="all" href="vendor/assets/stylesheets/animate.css">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script>new WOW().init();</script>
  </head>
  <body class="root_body">
    <%= render 'layouts/header' %>
    <div class="container">
      
      <%= button_to "Scroll Up", "javascript:topFunction()", id: "go_top_btn" %>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  ***Where must be detailed information about application***
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  ***Where must be contact information***
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  ***Where must be some help-info about application***
</p>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>

<div class="main_pic">
    <br /><br /><br /><br />
    <div class="greeting_text">
        <h1 class="greeting_text">Find the lowest price on the right hotel for you</h1>
    </div>
    <div class="slogan_text">
        <center><h2><strong>
'Hotel App' is the only hotel site that sends special investigators to visit, 
photograph, review, and rate each hotel. We inspect in-person — just like your 
mother-in-law.
        </strong></h2></center></div>
    </div>

<div class="center hero-unit main-page">
	
	<%= render 'blocks/preview' %>
    <br />
    <%= render 'blocks/preview' %>
    <br />
    <%= render 'blocks/preview' %>
    <br />
    <%= render 'blocks/preview' %>
    <br />
    <%= render 'blocks/preview' %>
    <br />
    <h1 class="wow fadeInRight">
        <%= link_to "Watch full list on hotels", listOfHotels_path, 
        class: "btn btn-default btn-large", id: "open_list_btn" %>
    </h1>
    <br />
    
</div>

app/views/static_pages/listOfHotels.html.erb
<% provide(:title, '') %>
<div class="center hero-unit">
    <h1>Full list of hotels</h1>
    <hr />
    <center>
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
        <br />
        <%= render 'blocks/preview' %>
    </center>
</div>

app/views/static_pages/pageh.html.erb
<% provide(:title, '') %>
<div class="center hero-unit">
    <h1>Full describtion about hotel</h1>
    <hr />
    <div class="div_descr_1">
        div 1 <br />
        Place for picture <br />
    </div>
    <div class="div_descr_2">
        div 2 <br />
        Place for full describtion.... <br />
    </div>
    <div class="div_descr_3">
        div 3 <br />
        Rating and vota-button <br />
    </div>
    <div class="div_descr_4">
        div 4 <br />
        Commentaries... <br />
    </div>
    
    <div class="clear"></div>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>	

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <% if @user.hotels.any? %>
      <% @hotel.each do |hotel| %>
        <%= render :partial => 'blocks/preview', 
                    :locals => {:hotel => hotel} %>
        <%= link_to 'Edit', edit_hotel_path(hotel) %>
        <%= link_to 'Destroy', hotel_path(hotel),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
      <% end %>
    <%= will_paginate @hotel %>
  <% end %>
</div>